export const defaultLayoutData = [
  {
    w: 2,
    h: 2,
    x: 0,
    y: 0,
    i: "orderNo",
    type: "orderNo",
  },
  {
    w: 2,
    h: 2,
    x: 8,
    y: 0,
    i: "causeNo",
    type: "causeNo",
  },
  {
    w: 2,
    h: 3,
    x: 4,
    y: 3,
    i: "attorney",
    type: "attorney",
  },
  {
    w: 2,
    h: 2,
    x: 8,
    y: 2,
    i: "offense",
    type: "offense",
  },
  {
    w: 2,
    h: 5,
    x: 8,
    y: 4,
    i: "offenseDate",
    type: "offenseDate",
  },
];

export const layoutSelectOptionsData = {
  orderNo: "Order No",
  startTime: "Start Time",
  causeNo: "Case No",
  caseAge: "Case Age",
  offense: "Offense / Case Type",
  offenseDate: "Offense Date",
  style: "Style",
  defendant: "Defendant",
  filingDate: "Filing Date",
  attorney: "Attorney",
  bondsmen: "Bondsmen",
  hearingType: "Hearing Type",
  notes: "Notes",
  otherParties: "Other Parties",
  bondAmount: "Bond Amount",
  defendantAddress: "Defendant Address",
  dateOfBirth: "Date of Birth",
  location: "Location",
  bondType: "Bond Type",
  defendantAttorney: "Defendant Attorney",
  plaintiffAttorney: "Plaintiff Attorney",
  courtAppointedAttorney: "Court Appointed Attorney",
};
