export const defaultLayoutData = [
  {
    w: 2,
    h: 1,
    x: 0,
    y: 0,
    i: "orderNo",
  },
  {
    w: 2,
    h: 1,
    x: 2,
    y: 0,
    i: "causeNo",
  },
  {
    w: 2,
    h: 1,
    x: 4,
    y: 0,
    i: "attorney",
  },
  {
    w: 2,
    h: 1,
    x: 6,
    y: 0,
    i: "offense",
  },
  {
    w: 2,
    h: 1,
    x: 8,
    y: 0,
    i: "offenseDate",
  },
];

export const layoutAllHeaders = {
  orderNo: "Order No",
  startTime: "Start Time",
  causeNo: "Case No",
  caseAge: "Case Age",
  offense: "Offense / Case Type",
  offenseDate: "Offense Date",
  style: "Style",
  defendant: "Defendant",
  filingDate: "Filing Date",
  attorney: "Attorney",
  bondsmen: "Bondsmen",
  hearingType: "Hearing Type",
  notes: "Notes",
  otherParties: "Other Parties",
  bondAmount: "Bond Amount",
  defendantAddress: "Defendant Address",
  dateOfBirth: "Date of Birth",
  location: "Location",
  bondType: "Bond Type",
  defendantAttorney: "Defendant Attorney",
  plaintiffAttorney: "Plaintiff Attorney",
  courtAppointedAttorney: "Court Appointed Attorney",
};

export const mockDocketData = [
  {
    orderNo: "2024-001",
    startTime: "09:00 AM",
    causeNo: "CR-2024-1234",
    caseAge: "127 days",
    offense: "Aggravated Assault",
    offenseDate: "2023-12-15",
    style: "State vs. Smith",
    defendant: "John Smith",
    filingDate: "2024-01-05",
    attorney: "James Wilson",
    bondsmen: "Liberty Bonds LLC",
    hearingType: "Initial Appearance",
    notes: "Defendant requests continuance due to medical reasons",
    otherParties: "Witness: Mary Johnson",
    bondAmount: "$25,000",
    defendantAddress: "123 Oak Street, Austin, TX 78701",
    dateOfBirth: "1985-06-15",
    location: "Courtroom 3A",
    bondType: "Surety Bond",
    defendantAttorney: "Michael Brown",
    plaintiffAttorney: "Sarah Davis",
    courtAppointedAttorney: null,
  },
  {
    orderNo: "2024-002",
    startTime: "09:30 AM",
    causeNo: "CV-2024-5678",
    caseAge: "45 days",
    offense: "Civil Dispute",
    offenseDate: "2024-01-20",
    style: "Johnson vs. Anderson Corp",
    defendant: "Anderson Corp",
    filingDate: "2024-02-01",
    attorney: "Lisa Martinez",
    bondsmen: null,
    hearingType: "Status Conference",
    notes: "Settlement negotiations ongoing",
    otherParties: "Expert Witness: Dr. Robert Lee",
    bondAmount: null,
    defendantAddress: "456 Corporate Blvd, Austin, TX 78702",
    dateOfBirth: null,
    location: "Courtroom 2B",
    bondType: null,
    defendantAttorney: "Thomas Wright",
    plaintiffAttorney: "Patricia Miller",
    courtAppointedAttorney: null,
  },
  {
    orderNo: "2024-003",
    startTime: "10:00 AM",
    causeNo: "CR-2024-2468",
    caseAge: "90 days",
    offense: "Drug Possession",
    offenseDate: "2024-01-01",
    style: "State vs. Williams",
    defendant: "Robert Williams",
    filingDate: "2024-01-15",
    attorney: "David Chen",
    bondsmen: "AAA Bail Bonds",
    hearingType: "Arraignment",
    notes: "Defendant in custody",
    otherParties: "Officer Mike Thompson",
    bondAmount: "$10,000",
    defendantAddress: "789 Pine Ave, Austin, TX 78703",
    dateOfBirth: "1992-03-22",
    location: "Courtroom 1C",
    bondType: "Cash Bond",
    defendantAttorney: "Jennifer Lopez",
    plaintiffAttorney: "Mark Wilson",
    courtAppointedAttorney: "Jennifer Lopez",
  },
  {
    orderNo: "2024-004",
    startTime: "10:30 AM",
    causeNo: "CV-2024-9012",
    caseAge: "30 days",
    offense: "Property Dispute",
    offenseDate: "2024-02-15",
    style: "Garcia vs. Martinez",
    defendant: "Elena Martinez",
    filingDate: "2024-02-28",
    attorney: "Richard Wong",
    bondsmen: null,
    hearingType: "Preliminary Hearing",
    notes: "Boundary dispute case",
    otherParties: "Surveyor: James Smith",
    bondAmount: null,
    defendantAddress: "321 Maple Dr, Austin, TX 78704",
    dateOfBirth: "1975-11-30",
    location: "Courtroom 4D",
    bondType: null,
    defendantAttorney: "Carlos Rodriguez",
    plaintiffAttorney: "Amy Chang",
    courtAppointedAttorney: null,
  },
  {
    orderNo: "2024-005",
    startTime: "11:00 AM",
    causeNo: "CR-2024-3690",
    caseAge: "60 days",
    offense: "DUI",
    offenseDate: "2024-01-30",
    style: "State vs. Brown",
    defendant: "Michael Brown",
    filingDate: "2024-02-10",
    attorney: "Sandra White",
    bondsmen: "Quick Release Bonds",
    hearingType: "Pre-trial Conference",
    notes: "Blood alcohol level: 0.12",
    otherParties: "Officer Sarah Johnson",
    bondAmount: "$5,000",
    defendantAddress: "567 Elm St, Austin, TX 78705",
    dateOfBirth: "1988-09-14",
    location: "Courtroom 2A",
    bondType: "Surety Bond",
    defendantAttorney: "Peter Parker",
    plaintiffAttorney: "Mary Jane",
    courtAppointedAttorney: null,
  },
  {
    orderNo: "2024-006",
    startTime: "11:30 AM",
    causeNo: "CV-2024-1122",
    caseAge: "75 days",
    offense: "Contract Breach",
    offenseDate: "2023-12-20",
    style: "Tech Corp vs. Smith Solutions",
    defendant: "Smith Solutions LLC",
    filingDate: "2024-01-10",
    attorney: "William Turner",
    bondsmen: null,
    hearingType: "Motion Hearing",
    notes: "Motion to dismiss pending",
    otherParties: "Expert: Dr. Emily Watson",
    bondAmount: null,
    defendantAddress: "890 Business Park, Austin, TX 78706",
    dateOfBirth: null,
    location: "Courtroom 5E",
    bondType: null,
    defendantAttorney: "George Harrison",
    plaintiffAttorney: "Paul McCartney",
    courtAppointedAttorney: null,
  },
  {
    orderNo: "2024-007",
    startTime: "1:00 PM",
    causeNo: "CR-2024-4567",
    caseAge: "15 days",
    offense: "Theft",
    offenseDate: "2024-02-25",
    style: "State vs. Taylor",
    defendant: "Emma Taylor",
    filingDate: "2024-03-01",
    attorney: "Robert Black",
    bondsmen: "Freedom Bail Bonds",
    hearingType: "Bail Hearing",
    notes: "First-time offense",
    otherParties: "Store Manager: John Doe",
    bondAmount: "$2,500",
    defendantAddress: "432 Cedar Ln, Austin, TX 78707",
    dateOfBirth: "1995-07-19",
    location: "Courtroom 1A",
    bondType: "Cash Bond",
    defendantAttorney: "Maria Garcia",
    plaintiffAttorney: "Steve Johnson",
    courtAppointedAttorney: "Maria Garcia",
  },
  {
    orderNo: "2024-008",
    startTime: "1:30 PM",
    causeNo: "CV-2024-7890",
    caseAge: "180 days",
    offense: "Medical Malpractice",
    offenseDate: "2023-09-15",
    style: "Thompson vs. Austin Medical Center",
    defendant: "Austin Medical Center",
    filingDate: "2023-10-01",
    attorney: "Elizabeth Green",
    bondsmen: null,
    hearingType: "Settlement Conference",
    notes: "Insurance representative present",
    otherParties: "Expert: Dr. Michael Stevens",
    bondAmount: null,
    defendantAddress: "100 Hospital Drive, Austin, TX 78708",
    dateOfBirth: null,
    location: "Courtroom 3C",
    bondType: null,
    defendantAttorney: "James Madison",
    plaintiffAttorney: "John Adams",
    courtAppointedAttorney: null,
  },
  {
    orderNo: "2024-009",
    startTime: "2:00 PM",
    causeNo: "CR-2024-5555",
    caseAge: "30 days",
    offense: "Burglary",
    offenseDate: "2024-02-10",
    style: "State vs. Anderson",
    defendant: "Chris Anderson",
    filingDate: "2024-02-20",
    attorney: "Michelle Lee",
    bondsmen: "Reliable Bail Bonds",
    hearingType: "Preliminary Hearing",
    notes: "Multiple prior offenses",
    otherParties: "Victim: Jane Smith",
    bondAmount: "$15,000",
    defendantAddress: "765 Birch St, Austin, TX 78709",
    dateOfBirth: "1982-12-03",
    location: "Courtroom 4B",
    bondType: "Surety Bond",
    defendantAttorney: "Bob Wilson",
    plaintiffAttorney: "Linda Clark",
    courtAppointedAttorney: "Bob Wilson",
  },
  {
    orderNo: "2024-010",
    startTime: "2:30 PM",
    causeNo: "CV-2024-3333",
    caseAge: "95 days",
    offense: "Employment Discrimination",
    offenseDate: "2023-12-01",
    style: "Martinez vs. Tech Solutions Inc",
    defendant: "Tech Solutions Inc",
    filingDate: "2023-12-15",
    attorney: "Daniel Brown",
    bondsmen: null,
    hearingType: "Case Management",
    notes: "EEOC documentation pending",
    otherParties: "HR Manager: Alice Johnson",
    bondAmount: null,
    defendantAddress: "999 Technology Pkwy, Austin, TX 78710",
    dateOfBirth: null,
    location: "Courtroom 5A",
    bondType: null,
    defendantAttorney: "Sarah Connor",
    plaintiffAttorney: "John Connor",
    courtAppointedAttorney: null,
  },
];
